name: connectflow_app
description: Prone - Professional Command Center for Application Backends
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.0.5
  
  # HTTP Client
  dio: ^5.4.0
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  path: ^1.8.3
  
  # Permissions
  permission_handler: ^11.1.0
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Routing
  go_router: ^13.0.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  uuid: ^4.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
